name: CI Build

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: pwsh

jobs:
  ci_build_windows:
    name: CI Windows Build
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [Win32, x64]
        configuration: [Debug, Release]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" -A ${{ matrix.architecture }} ..
        cmake --build . --config ${{ matrix.configuration }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MzingaCpp.Windows.${{ matrix.architecture }}.${{ matrix.configuration }}
        path: build/${{ matrix.configuration }}/*

  ci_build_linux:
    name: CI Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x64]
        configuration: [Debug, Release]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ matrix.configuration }}/
        cmake --build . --config ${{ matrix.configuration }}
    
    - name: Tar Files
      run: tar -C build/${{ matrix.configuration }} . -cvzf MzingaCpp.Linux.${{ matrix.architecture }}.${{ matrix.configuration }}.tar.gz

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MzingaCpp.Linux.${{ matrix.architecture }}.${{ matrix.configuration }}
        path: MzingaCpp.Linux.${{ matrix.architecture }}.${{ matrix.configuration }}.tar.gz