name: CI Build

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: pwsh

jobs:
  ci_build_windows:
    name: CI Windows Build
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [Win32, x64]
        configuration: [Debug, Release]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" -A ${{ matrix.architecture }} ..
        cmake --build . --config ${{ matrix.configuration }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Windows.${{ matrix.architecture }}.${{ matrix.configuration }}
        path: build/${{ matrix.configuration }}/*
