name: PR Validation

env:
  Product: MzingaCpp

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: pwsh

jobs:
  pr_build_windows:
    name: PR Windows Build
    runs-on: windows-2022
    strategy:
      matrix:
        architecture: [Win32]
        configuration: [Debug]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A ${{ matrix.architecture }} ..
        cmake --build . --config ${{ matrix.configuration }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.Product }}.Windows.${{ matrix.architecture }}.${{ matrix.configuration }}
        path: build/${{ matrix.configuration }}/*

  pr_build_linux:
    name: PR Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x64]
        configuration: [Debug]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ matrix.configuration }}/
        cmake --build . --config ${{ matrix.configuration }}

    - name: Tar Files
      run: tar -C build/${{ matrix.configuration }} . -cvzf ${{ env.Product }}.Linux.${{ matrix.architecture }}.${{ matrix.configuration }}.tar.gz

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.Product }}.Linux.${{ matrix.architecture }}.${{ matrix.configuration }}
        path: ${{ env.Product }}.Linux.${{ matrix.architecture }}.${{ matrix.configuration }}.tar.gz
